##################################################
# Copyright (C) 2017, All rights reserved.
##################################################

from __future__ import print_function
import argparse
import os
import sys

from pyprelude.file_system import make_path
from pysimplevcs.git import Git

from ignoregen import __description__, __project_name__, __version__
from ignoregen.config import Config

def _remove_prefix(prefix, s):
    if s.startswith(prefix):
        return s[len(prefix):]
    else:
        return None

def _get_names_to_ignore(search_dir):
    git = Git(search_dir)
    dir_names = set()
    file_names = set()
    for line in git.status("--ignored").splitlines():
        temp = _remove_prefix("#", line)
        if temp is None: continue

        temp = temp.strip()
        if len(temp) == 0: continue

        name = temp.split(os.sep)[0]
        path = make_path(search_dir, name)
        if os.path.isdir(path):
            dir_names.add(name)
        elif os.path.isfile(path):
            file_names.add(name)

    return dir_names, file_names

def _do_gen(config, args):
    dir_names, file_names = _get_names_to_ignore(os.path.expanduser("~"))
    print("# Automatically generated by {} version {}".format(__project_name__, __version__))
    for n in sorted(dir_names):
        print("/{}/".format(n))
    for n in sorted(file_names):
        print("/{}".format(n))

def _main(argv=None):
    if argv is None:
        argv = sys.argv[1:]

    config_dir = os.path.abspath(os.path.expanduser(os.environ.get("IGNOREGEN_DIR", "~/.ignoregen")))
    config = Config(config_dir)

    parser = argparse.ArgumentParser(prog=__project_name__, description=__description__)
    parser.add_argument("--version", action="version", version="{} version {}".format(__project_name__, __version__))

    subparsers = parser.add_subparsers(help="subcommand help")

    gen_parser = subparsers.add_parser("gen", help="Generate Git ignore rules")
    gen_parser.set_defaults(func=_do_gen)

    args = parser.parse_args(argv)
    args.func(config, args)

if __name__ == "__main__":
    _main()
